[tool.poetry]
name = "llm-pls"
version = "0.1.0"
description = "An API wrapper for when your language model is a little too big to initialize in every script"
authors = ["Logan Walls <2934282+LoganWalls@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
torch = "1.11.0"
numpy = "1.22.0"
mujoco = "^2.3.3"
gym = "0.17.2"
tensorboard = "^2.12.0"
contourpy = "^1.0.7"
cycler = "^0.11.0"
fonttools = "^4.39.2"
importlib-resources = "^5.12.0"
kiwisolver = "^1.4.4"
packaging = "^23.0"
Pillow = "^9.4.0"
pyparsing = "^3.0.9"
python-dateutil = "^2.8.2"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
ipdb = "^0.13.9"
ipython = "^8.4.0"
isort = "^5.10.1"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
